x-common-config: &common-config
  env_file:
    - path: .env
  build:
    context: .
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  api-gateway:
    <<: *common-config
    container_name: airank-core-api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - 4001:4001
    environment:
      - API_GATEWAY_PORT=4001
    networks:
      default:
        aliases:
          - api-gateway

  graphql:
    <<: *common-config
    container_name: airank-core-graphql
    build:
      context: .
      dockerfile: ./graphql/Dockerfile
    ports:
      - 4002:4002
    networks:
      default:
        aliases:
          - graphql

  batcher:
    <<: *common-config
    container_name: airank-core-batcher
    build:
      context: .
      dockerfile: ./batcher/Dockerfile
    networks:
      default:
        aliases:
          - batcher

  listener:
    <<: *common-config
    container_name: airank-core-listener
    build:
      context: .
      dockerfile: ./listener/Dockerfile
    networks:
      default:
        aliases:
          - listener
