x-common-config: &common-config
  env_file:
    - path: .env
  build:
    context: .
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  api-gateway:
    <<: *common-config
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - 3001:3001
    environment:
      - API_GATEWAY_PORT=3001

  graphql:
    <<: *common-config
    build:
      context: .
      dockerfile: ./graphql/Dockerfile
    ports:
      - 3002:3002

  batcher:
    <<: *common-config
    build:
      context: .
      dockerfile: ./batcher/Dockerfile
